default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  username: postgres

development:
  <<: *default
  password: postgres
  username: postgres
  database: loginapp_development

test:
  <<: *default
  password: postgres
  username: postgres
  database: loginapp_test

production:
  <<: *default
  password: postgres
  username: postgres
  database: loginapp_production